export const ASSIGN_SLOT_MODAL = 'ASSIGN_SLOT_MODAL';
export const REVIEW_MODAL = 'REVIEW_MODAL';
export const REJECT_MODAL = 'REJECT_MODAL';
export const APPROVE_MODAL = 'APPROVE_MODAL';

export const MODAL_TYPES = {
  ASSIGN_SLOT_MODAL: ASSIGN_SLOT_MODAL,
  REVIEW_MODAL: REVIEW_MODAL,
  REJECT_MODAL: REJECT_MODAL,
  APPROVE_MODAL: APPROVE_MODAL,
  ASSIGN_SLOT_COMPONENT_CP: 'ASSIGN_SLOT_COMPONENT_CP',
  SEND_FOR_REVIEW_MODAL: 'SEND_FOR_REVIEW_MODAL',
  SEND_ALL_SLOTS_REVIEW_MODAL: 'SEND_ALL_SLOTS_REVIEW_MODAL',
};

export const STATUS_ACTION_TYPE = {
  Assign : 'Assign',
  Send : 'Send',
  Reject : 'Reject',
  Approve : 'Approve',
}
