import { MAX_COMPONENTS_PER_SLOT, MAX_SEARCH_FILTER_INPUT_LENGTH, MAX_SLOTS } from "./commonConstants";

export const UI_TEXTS = {
  ERRORS: {
    COMPONENT_TYPE_MISMATCH: "Component type must be same in a slot",
    WIREFRAME_DELETE_FAILED: "Failed to delete wireframe",
    WIREFRAME_DUPLICATE_FAILED: "Failed to duplicate wireframe",
    URL_CREATION_FAILED: "Failed to create URL",
    URL_EDIT_FAILED: "Failed to edit URL",
    WIREFRAME_ARCHIVE_FAILED: "Failed to archive wireframe",
  },
  SLOT: {
    TITLE_LABEL: "Key Slot Message",
    BLANK_MESSAGE: "Drag & Drop Component",
    MISMATCH_MESSAGE: "Select same component to place here",
    CONFIGURATION_LABEL: "Slot Configuration",
    DUPLICATE_LABEL: "Duplicate Slot",
    MOVE_UP_LABEL: "Move Slot Up",
    MOVE_DOWN_LABEL: "Move Slot Down",
    ASSIGN_SLOT_LABEL: "Assign Slot",
    ASSIGN_COMPONENT_LABEL: "Assign Component",
    DELETE_LABEL: "Delete",
    DELETE_SLOT: "Delete Slot",
    DELETE_SLOT_MESSAGE: "Are you sure you want to delete this slot?",
    SEND_SLOT_FOR_REVIEW: "Send Slot for Review",
    APPROVE_SLOT: "Approve Slot",
    REJECT_SLOT: "Reject Slot",
    REJECT_COMPONENT: "Reject Component",
    SEND_ALL_SLOTS_FOR_REVIEW: "Send All Slots for Review",
  },
  COMPONENT: {
    CONFIGURATION_LABEL: "Component Configuration",
    DUPLICATE_LABEL: "Duplicate Component on Right",
    DELETE_LABEL: "Delete Component",
    ASSIGN_LABEL: "Assign Component",
    BANNER_CALL_OUT: "Banner Call Out",
    SEND_COMPONENT_FOR_REVIEW: "Send Component for Review",
    APPROVE_COMPONENT: "Approve Component",
    REJECT_COMPONENT: "Reject Component",
    PICK_START_WORK: "Pick & Start Work"
  },
  BUTTONS: {
    ADD_SLOT: "Add Slot",
  },
  SELECT: {
    ALL: "All",
  },
  ACTIONS: {
    OPEN_IN_EDITOR: "Open in Editor",
    PAGE_CONFIGURATION: "Page Configuration",
    COPY_PAGE: "Copy Page",
    ASSIGN_PAGE: "Assign Page",
    SEND_PAGE_FOR_REVIEW: "Send Page for Review",
    APPROVE_PAGE: "Approve Page",
    REJECT_PAGE: "Reject Page",
    ARCHIVE_PAGE: "Archive Page",
    ARCHIEVE: "Archive",
    COPY_THE_PAGE: "Copy the page",
  },
  LABEL: {
    ARCHIVE_TITLE_LABEL: "Are you sure you want to archive?",
    COPY_TITLE_LABEL: "Are you sure you want to copy this wireframe?",
    CREATE_URL_MAPPING_LABEL: "Create URL Mapping",
    EDIT_URL_MAPPING_LABEL: "Edit URL Mapping",
  },
  DESCRIPTION: {
    COPY_WIREFRAME: "Copy Wireframe",
    UNIQUE_PER_STORE_AND_PLATFORM: "Must be unique per store and platform"
  },
  MESSAGES: {
    WIREFRAME_DELETED_SUCCESS: "Wireframe deleted successfully",
    WIREFRAME_ARCHIVED_SUCCESS: "Wireframe archived successfully",
    URL_CREATED_SUCCESS: "New URL created",
    URL_UPDATED_SUCCESS: "URL updated",
    CANNOT_ADD_MORE_SLOTS: `Cannot add more than ${MAX_SLOTS} slots`,
    CANNOT_ADD_MORE_COMPONENTS: `Cannot add more than ${MAX_COMPONENTS_PER_SLOT} components in a slot`,
    CANNOT_ENTER_MORE_THAN_MAX_CHARACTERS: `Cannot enter more than ${MAX_SEARCH_FILTER_INPUT_LENGTH} characters`,
    AT_LEAST_ONE_SLOT_REQUIRED: "At least one slot must remain. Deletion not allowed.",
  },
  URL_MODAL_TEXT: {
    PAGE_NAME_REQUIRED: "Page name is required",
    SLUG_REQUIRED: "Slug is required",
    INVALID_DATE_FORMAT: "Invalid date format",
    START_REQUIRED_WHEN_SCHEDULED:
      "Start date & time is required when scheduled.",
    END_REQUIRED_WHEN_SCHEDULED: "End date & time is required when scheduled.",
    PLATFORM_REQUIRED: "Platform is required",
    STORE_REQUIRED: "Store is required",
    PAGE_ID_REQUIRED: "Wireframe/Page selection is required",
    URl_SLUG: "URL Slug",
  },
  platform: "Platform",
  pageUrl: "Page & URL",
  page: "Page",
  storemapping: "Store Mapping",
  userCohort: "User Cohort",
  scheduler: "Scheduler",
  updateUrl: "Update URL",
  createUrl: "Create URL",
};
